export const LoadsListTableData = [
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
];

export const loadsActivity = [
  {
    loadsText: "Loads Available",
    ratio: "512",
    percentage: "+2.5%",
    comparedTo: 340,
  },
  {
    loadsText: "Loads Covered",
    ratio: "25",
    percentage: "-1.5%",
    comparedTo: 28,
  },
  {
    loadsText: "Loads in Transit",
    ratio: "125",
    percentage: "+0.5%",
    comparedTo: 120,
  },
  {
    loadsText: "Loads Earning",
    ratio: "$12632",
    percentage: "+2.5%",
    comparedTo: 10500,
  },
  {
    loadsText: "Carrier Number",
    ratio: "12",
    percentage: "+2.5%",
    comparedTo: 11,
  },
];

export const dataRaw = [
  {
    name: "Jan",
    uv: 800,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Feb",
    uv: 500,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Mar",
    uv: 1000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Apr",
    uv: 900,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "May",
    uv: 1000,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Jun",
    uv: 1400,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Jul",
    uv: 2000,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Aug",
    uv: 1600,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Sep",
    uv: 2000,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Oct",
    uv: 1600,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Nov",
    uv: 2000,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Dec",
    uv: 3800,
    pv: 4300,
    amt: 2100,
  },
];
